import { fileURLToPath, URL } from 'node:url'
import fs from 'node:fs'
import glob from 'fast-glob'

const resolve = (p) => fileURLToPath(new URL(p, import.meta.url))
const getName = (filepath) => {
  let t = filepath.slice(0, -5)
  if (t.endsWith('/index')) t = t.slice(0, -6)
  return t
}

async function start() {
  const HTMLFiles = await glob(['./**/*.html'], {
    ignore: ['./index.html'],
    cwd: resolve('.'),
  })
  HTMLFiles.sort()
  const result = HTMLFiles.map((filepath) => {
    const arr = filepath.split('/')
    return `<li><a href="./${filepath}">${getName(filepath)}</a></li>`
  }).join('\n')
  fs.writeFile(
    resolve('./index.html'),
    `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>UI</title>
        <link rel="stylesheet" href="./index.css" />
      </head>
      <body>
        <!-- generated by ./index.mjs -->
        <h1>UI</h1>
        <ul>
          ${result}
        </ul>
      </body>
    </html>
  `,
    (err) => {}
  )
}

start()
